version: 3

includes:
  go:
    taskfile: templates/taskfiles/go.yml
    optional: true
  docker:
    taskfile: templates/taskfiles/docker.yml
    optional: true


tasks:
  submodule:
    cmds:
      - git submodule update --remote --recursive
    desc: Update submodules

  gen:
    cmds:
      - go generate ./...
    desc: Run go generate on the project

  unit-test:
    desc: "Running unit Tests"
    cmds:
      - go test -coverprofile cover.out ./...
      - go tool cover -html=cover.out -o cover.html
      - go-cover-treemap -coverprofile cover.out > assets/cover-treemap.svg